name: java 21
on: push 
jobs: 
  java-job: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
            distribution: 'temurin'
            java-version: '21'
            # cache: 'maven'
            # cache-dependency-path: 'sub-project/pom.xml' # optional
            -run: echo java --version
